INSERT INTO CT_ESTATUS_TRANSMISION (FC_ESTATUS_TRANSMISION) VALUES ('Por procesar');
INSERT INTO CT_ESTATUS_TRANSMISION (FC_ESTATUS_TRANSMISION) VALUES ('Procesando');
INSERT INTO CT_ESTATUS_TRANSMISION (FC_ESTATUS_TRANSMISION) VALUES ('Publicación a Kafka');
INSERT INTO CT_ESTATUS_TRANSMISION (FC_ESTATUS_TRANSMISION) VALUES ('Error al publicar en Kafka');
INSERT INTO CT_ESTATUS_TRANSMISION (FC_ESTATUS_TRANSMISION) VALUES ('Error al parsear el evento');
COMMIT;