--------------------------------------------------------------------------------
------------------------------------------------------ CATÁLOGO TOPICOS KAFKA
--------------------------------------------------------------------------------
CREATE TABLE URSCTRLBO.CT_TOPICO_KAFKA 
(
    FI_ID_TOPICO_KAFKA NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FC_TOPICO_KAFKA VARCHAR2(80) UNIQUE NOT NULL ENABLE 
    ,FC_DESCRIPCION VARCHAR2(80) NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE 
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_TOPICO_KAFKA ON URSCTRLBO.CT_TOPICO_KAFKA (FI_ID_TOPICO_KAFKA, FC_TOPICO_KAFKA) TABLESPACE TS_IX_CTRLBO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.CT_TOPICO_KAFKA ADD ( CONSTRAINT PK_CT_TOPICO_KAFKA PRIMARY KEY (FI_ID_TOPICO_KAFKA) USING INDEX);


--------------------------------------------------------------------------------
------------------------------------------------------ CATÁLOGO CONSUMIDORES KAFKA
--------------------------------------------------------------------------------
CREATE TABLE URSCTRLBO.CT_CONSUMIDOR_KAFKA 
(
    FI_ID_CONSUMIDOR_KAFKA NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FC_CONSUMIDOR_KAFKA VARCHAR2(50) NOT NULL ENABLE 
    ,FC_DESCRIPCION VARCHAR2(80) NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;


------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_CONSUMER_KFK ON URSCTRLBO.CT_CONSUMIDOR_KAFKA (FI_ID_CONSUMIDOR_KAFKA, FC_CONSUMIDOR_KAFKA) TABLESPACE TS_IX_CTRLBO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.CT_CONSUMIDOR_KAFKA ADD ( CONSTRAINT PK_CONSUMER_KFK PRIMARY KEY (FI_ID_CONSUMIDOR_KAFKA) USING INDEX);


--------------------------------------------------------------------------------
------------------------------------------------------ CATÁLOGO PERMISOS TÓPICO
--------------------------------------------------------------------------------
CREATE TABLE URSCTRLBO.CT_PERMISO_TOPICO
(
    FI_ID_PERMISO_TOPICO NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FC_PERMISO_TOPICO VARCHAR2(30) NOT NULL ENABLE 
    ,FC_DESCRIPCION VARCHAR2(80) NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_PERM_TOPICO ON URSCTRLBO.CT_PERMISO_TOPICO (FI_ID_PERMISO_TOPICO, FC_PERMISO_TOPICO) TABLESPACE TS_IX_CTRLBO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.CT_PERMISO_TOPICO ADD ( CONSTRAINT PK_PERMISO_TOPICO PRIMARY KEY (FI_ID_PERMISO_TOPICO) USING INDEX);

--------------------------------------------------------------------------------
------------------------------------------------------ CATÁLOGO ESTATUS TRANSMISIÓN
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.CT_ESTATUS_TRANSMISION
(
    FI_ID_ESTATUS_TRANSMISION NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FC_ESTATUS_TRANSMISION VARCHAR2(20) NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_EST_TRANSMI ON URSCTRLBO.CT_ESTATUS_TRANSMISION (FI_ID_ESTATUS_TRANSMISION, FC_ESTATUS_TRANSMISION) TABLESPACE TS_IX_CTRLBO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.CT_ESTATUS_TRANSMISION ADD ( CONSTRAINT PK_ESTATUS_TRANSMISION PRIMARY KEY (FI_ID_ESTATUS_TRANSMISION) USING INDEX);

--------------------------------------------------------------------------------
------------------------------------------------------ CATÁLOGO TIPO TRANSACCIONES
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.CT_TIPO_TRANSACCION
(
    FI_ID_TIPO_TRANSACCION NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FC_TIPO_TRANSACCION VARCHAR2(50) NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_TIPO_TRANSAC ON URSCTRLBO.CT_TIPO_TRANSACCION (FI_ID_TIPO_TRANSACCION, FC_TIPO_TRANSACCION) TABLESPACE TS_IX_CTRLBO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.CT_TIPO_TRANSACCION ADD ( CONSTRAINT PK_TIPO_TRANSACCION PRIMARY KEY (FI_ID_TIPO_TRANSACCION) USING INDEX);

--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE REGISTRO DE USUARIO
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_USUARIO_REGISTRO
(
    FI_ID_USUARIO_REGISTRO NUMBER GENERATED ALWAYS AS IDENTITY
    ,FC_USUARIO_REGISTRO VARCHAR2(30) NOT NULL ENABLE
    ,FI_TIPO_USUARIO NUMBER NOT NULL ENABLE
    ,FC_DESCRIPCION VARCHAR2(80) NOT NULL ENABLE 
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_USR_REGISTRO ON URSCTRLBO.TA_USUARIO_REGISTRO (FI_ID_USUARIO_REGISTRO) TABLESPACE TS_IX_CTRLBO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.TA_USUARIO_REGISTRO ADD ( CONSTRAINT PK_USR_REGISTRO PRIMARY KEY (FI_ID_USUARIO_REGISTRO) USING INDEX);


--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE ESQUEMAS AVRO
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_ESQUEMA_AVRO
(
    FI_ID_ESQUEMA_AVRO NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FI_ID_TOPICO_KAFKA NUMBER NOT NULL ENABLE
    ,FC_DESCRIPCION VARCHAR2(80) NOT NULL ENABLE
    ,FC_AVRO CLOB NOT NULL ENABLE    
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_ESQUEMA_AVRO ON URSCTRLBO.TA_ESQUEMA_AVRO (FI_ID_ESQUEMA_AVRO) TABLESPACE TS_IX_CTRLBO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.TA_ESQUEMA_AVRO ADD ( CONSTRAINT PK_ESQUEMA_AVRO PRIMARY KEY (FI_ID_ESQUEMA_AVRO) USING INDEX);


--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE OPERACIONES POR TOPICO
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_TOPICO_OPERACION
(
    FI_ID_TOPICO_OPERACION NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FI_ID_PERMISO_TOPICO NUMBER NOT NULL ENABLE
    ,FC_OPERACION VARCHAR2(50) NOT NULL ENABLE
    ,FC_DESCRIPCION VARCHAR2(80)
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_TOPICO_OPER ON URSCTRLBO.TA_TOPICO_OPERACION (FI_ID_TOPICO_OPERACION) TABLESPACE TS_IX_CTRLBO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.TA_TOPICO_OPERACION ADD ( CONSTRAINT PK_TOPICO_OPER PRIMARY KEY (FI_ID_TOPICO_OPERACION) USING INDEX);

--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE TOPICOS CONSUMIDOR DE KAFKA
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_TOPICO_CONSUMIDOR_KAFKA
(
    FI_ID_TOPICO_KAFKA NUMBER NOT NULL ENABLE
    ,FI_ID_CONSUMIDOR_KAFKA NUMBER NOT NULL ENABLE
    ,FI_ID_PERMISO_TOPICO NUMBER NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_TOPICO_CONSU
    ON URSCTRLBO.TA_TOPICO_CONSUMIDOR_KAFKA (FI_ID_TOPICO_KAFKA, FI_ID_CONSUMIDOR_KAFKA, FI_ID_PERMISO_TOPICO)
TABLESPACE TS_IX_CTRLBO NOLOGGING;
--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE ESQUEMAS DE TRANSACCIÓN
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_TRANSACCION_ESQUEMA
(
    FI_ID_TIPO_TRANSACCION NUMBER NOT NULL ENABLE
    ,FI_ID_ESQUEMA_AVRO NUMBER NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_TRANSA_ESQUE
    ON URSCTRLBO.TA_TRANSACCION_ESQUEMA (FI_ID_TIPO_TRANSACCION, FI_ID_ESQUEMA_AVRO)
TABLESPACE TS_IX_CTRLBO NOLOGGING;

--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE EVENTOS DE COBRE BANCARIO
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_EVENTO_CB
(
    FI_ID_TRANSACCION NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FI_ID_USUARIO_REGISTRO NUMBER NOT NULL ENABLE
    ,FI_ID_ESTATUS_TRANSMISION NUMBER NOT NULL ENABLE
    ,FI_ID_TIPO_TRANSACCION NUMBER NOT NULL ENABLE
    ,FD_FECHA_REGISTRO DATE NOT NULL ENABLE
    ,FC_SISTEMA_REGISTRO VARCHAR2(50) NOT NULL ENABLE
    ,FC_JSON CLOB
    ,FC_ID_WORKER VARCHAR2(50)
    ,FD_FECHA_LECTURA DATE
    ,FD_FECHA_PROCESAMIENTO DATE
    ,FC_KAFKA_ID VARCHAR(20)
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_EVT_ID_TRANS ON URSCTRLBO.TA_EVENTO_CB (FI_ID_TRANSACCION) TABLESPACE TS_IX_CTRLBO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.TA_EVENTO_CB ADD ( CONSTRAINT PK_EVT_ID_TRANSM PRIMARY KEY (FI_ID_TRANSACCION) USING INDEX);


--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE CATALOGOS
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.CT_CATALOGO_CB
(
    FI_ID_CATALOGO NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FC_DESCRIPCION VARCHAR(80) NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRLBO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_CT_ID_CAT ON URSCTRLBO.CT_CATALOGO_CB (FI_ID_CATALOGO) TABLESPACE TS_IX_CTRLBO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.CT_CATALOGO_CB ADD ( CONSTRAINT PK_ID_CAT_CAT PRIMARY KEY (FI_ID_CATALOGO) USING INDEX);


--------------------------------------------------------------------------------
------------------------------------------------------ CONSTRAINTS DE LLAVES FORANEAS
--------------------------------------------------------------------------------

-------------- CREACIÓN DE CONSTRAINT PARA FK DE TA_ESQUEMA_AVRO
ALTER TABLE URSCTRLBO.TA_ESQUEMA_AVRO ADD (
    CONSTRAINT FK_ESQ_AVRO_TOPICO FOREIGN KEY (FI_ID_TOPICO_KAFKA) 
    REFERENCES URSCTRLBO.CT_TOPICO_KAFKA (FI_ID_TOPICO_KAFKA)
);


-------------- CREACIÓN DE CONSTRAINT PARA FK DE TA_TOPICO_OPERACION
ALTER TABLE URSCTRLBO.TA_TOPICO_OPERACION ADD (
    CONSTRAINT FK_TOPICO_OPER_PERMISO FOREIGN KEY (FI_ID_PERMISO_TOPICO) 
    REFERENCES URSCTRLBO.CT_PERMISO_TOPICO (FI_ID_PERMISO_TOPICO)
);


-------------- CREACIÓN DE CONSTRAINT PARA FK DE TA_TOPICO_CONSUMIDOR_KAFKA
ALTER TABLE URSCTRLBO.TA_TOPICO_CONSUMIDOR_KAFKA ADD (
    CONSTRAINT FK_TOPICO_CONSU_TOPICO FOREIGN KEY (FI_ID_TOPICO_KAFKA) 
    REFERENCES URSCTRLBO.CT_TOPICO_KAFKA (FI_ID_TOPICO_KAFKA)
);

ALTER TABLE URSCTRLBO.TA_TOPICO_CONSUMIDOR_KAFKA ADD (
    CONSTRAINT FK_TOPICO_CONSU FOREIGN KEY (FI_ID_CONSUMIDOR_KAFKA) 
    REFERENCES URSCTRLBO.CT_CONSUMIDOR_KAFKA (FI_ID_CONSUMIDOR_KAFKA)
);

ALTER TABLE URSCTRLBO.TA_TOPICO_CONSUMIDOR_KAFKA ADD (
    CONSTRAINT FK_TOPICO_CONSU_PERMI FOREIGN KEY (FI_ID_PERMISO_TOPICO) 
    REFERENCES URSCTRLBO.CT_PERMISO_TOPICO (FI_ID_PERMISO_TOPICO)
);


-------------- CREACIÓN DE CONSTRAINT PARA FK DE TA_TRANSACCION_ESQUEMA
ALTER TABLE URSCTRLBO.TA_TRANSACCION_ESQUEMA ADD (
    CONSTRAINT FK_TRANSACC_TIPO_ESQUEMA FOREIGN KEY (FI_ID_TIPO_TRANSACCION) 
    REFERENCES URSCTRLBO.CT_TIPO_TRANSACCION (FI_ID_TIPO_TRANSACCION)
);

ALTER TABLE URSCTRLBO.TA_TRANSACCION_ESQUEMA ADD (
    CONSTRAINT FK_TRANSACC_ESQUEMA FOREIGN KEY (FI_ID_ESQUEMA_AVRO) 
    REFERENCES URSCTRLBO.TA_ESQUEMA_AVRO (FI_ID_ESQUEMA_AVRO)
);


-------------- CREACIÓN DE CONSTRAINT PARA FK DE TA_EVENTO_CB
ALTER TABLE URSCTRLBO.TA_EVENTO_CB ADD (
    CONSTRAINT FK_EVENTO_USUARIO FOREIGN KEY (FI_ID_USUARIO_REGISTRO) 
    REFERENCES URSCTRLBO.TA_USUARIO_REGISTRO (FI_ID_USUARIO_REGISTRO)
);

ALTER TABLE URSCTRLBO.TA_EVENTO_CB ADD (
    CONSTRAINT FK_EVENTO_TRANSMISION FOREIGN KEY (FI_ID_ESTATUS_TRANSMISION) 
    REFERENCES URSCTRLBO.CT_ESTATUS_TRANSMISION (FI_ID_ESTATUS_TRANSMISION)
);

ALTER TABLE URSCTRLBO.TA_EVENTO_CB ADD (
    CONSTRAINT FK_EVENTO_TIPO_TRANSM FOREIGN KEY (FI_ID_TIPO_TRANSACCION) 
    REFERENCES URSCTRLBO.CT_TIPO_TRANSACCION (FI_ID_TIPO_TRANSACCION)
);