--------------------------------------------------------------------------------
------------------------------------------------------ CATÁLOGO TOPICOS KAFKA
--------------------------------------------------------------------------------
CREATE TABLE URSCTRLBO.CT_TOPICO_KAFKA 
(
    FI_ID_TOPICO_KAFKA GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE,
    FC_TOPICO_KAFKA VARCHAR2(80) UNIQUE NOT NULL ENABLE 
    ,FC_DESCRIPCION VARCHAR2(80)  
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE 
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_TA_CTRL_BO;

------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_TOPICO_KAFKA ON URSCTRLBO.CT_TOPICO_KAFKA (FI_ID_TOPICO_KAFKA, FC_TOPICO_KAFKA) TABLESPACE TS_IX_CTRL_BO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.CT_TOPICO_KAFKA ADD ( CONSTRAINT PK_CT_TOPICO_KAFKA PRIMARY KEY (FI_ID_TOPICO_KAFKA) USING INDEX);


--------------------------------------------------------------------------------
------------------------------------------------------ CATÁLOGO CONSUMIDORES KAFKA
--------------------------------------------------------------------------------
CREATE TABLE URSCTRLBO.CT_CONSUMIDOR_KAFKA 
(
    FI_ID_CONSUMIDOR_KAFKA NUMBER NOT NULL ENABLE
    ,FC_CONSUMIDOR_KAFKA VARCHAR2(50) NOT NULL ENABLE 
    ,FC_DESCRIPCION VARCHAR2(80) 
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_CTRL_BO;


------------ CREACIÓN DE ÍNDICE
CREATE UNIQUE INDEX URSCTRLBO.IX_CONSUMER_KFK ON URSCTRLBO.CT_TOPICO_KAFKA (FI_ID_TOPICO_KAFKA, FC_TOPICO_KAFKA) TABLESPACE TS_IX_CTRL_BO NOLOGGING;

------------ CREACIÓN DE CONSTRAINT PARA PK
ALTER TABLE URSCTRLBO.CT_TOPICO_KAFKA ADD ( CONSTRAINT PK_CONSUMER_KFK PRIMARY KEY (FI_ID_TOPICO_KAFKA) USING INDEX);

--------------------------------------------------------------------------------
------------------------------------------------------ CATÁLOGO PERMISOS TÓPICO
--------------------------------------------------------------------------------
CREATE TABLE URSCTRLBO.CT_PERMISO_TOPICO
(
    FI_ID_PERMISO_TOPICO NUMBER NOT NULL ENABLE
    ,FC_PERMISO_TOPICO VARCHAR2(30) NOT NULL ENABLE 
    ,FC_DESCRIPCION VARCHAR2(80) 
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_CTRL_BO;



--------------------------------------------------------------------------------
------------------------------------------------------ CATÁLOGO ESTATUS TRANSMISIÓN
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.CT_ESTATUS_TRANSMISION
(
    FI_ID_ESTATUS_TRANSMISION NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FC_ESTATUS_TRANSMISION VARCHAR2(20) NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_CTRL_BO;


--------------------------------------------------------------------------------
------------------------------------------------------ CATÁLOGO TIPO TRANSACCIONES
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.CT_TIPO_TRANSACCION
(
    FI_ID_TIPO_TRANSACCION NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FC_TIPO_TRANSACCION VARCHAR2(50) NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_CTRL_BO;


--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE REGISTRO DE USUARIO
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_USUARIOS_REGISTRO
(
    FI_ID_USUARIO_REGISTRO NUMBER GENERATED ALWAYS AS IDENTITY
    ,FC_USUARIO_REGISTRO VARCHAR2(30) NOT NULL ENABLE
    ,FI_TIPO_USUARIO NUMBER NOT NULL ENABLE
    ,FC_DESCRIPCION VARCHAR2(80) 
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
) TABLESPACE TS_CTRL_BO;


--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE ESQUEMAS AVRO
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_ESQUEMA_AVRO
(
    FI_ID_ESQUEMA_AVRO NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FI_ID_TOPICO_KAFKA NUMBER NOT NULL ENABLE
    ,FC_DESCRIPCION VARCHAR2(80)
    ,FC_AVRO CLOB NOT NULL ENABLE    
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
    ,CONSTRAINT FK_ESQUEMA_TOPICO FOREIGN KEY (FI_ID_TOPICO_KAFKA) REFERENCES CT_TOPICO_KAFKA (FI_ID_TOPICO_KAFKA)
) TABLESPACE TS_CTRL_BO;


-------------- CREACIÓN DE CONSTRAINT PARA FK
ALTER TABLE URSCTRLBO.TA_ESQUEMA_AVRO ADD (
    CONSTRAINT FK_AVRO_TOPICO FOREIGN KEY (FI_ID_TOPICO_KAFKA) 
    REFERENCES URSCTRLBO.CT_TOPICO_KAFKA (FI_ID_TOPICO_KAFKA)
);
--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE ESQUEMAS AVRO
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_TOPICO_OPERACION
(
    FI_ID_TOPICO_OPERACION NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FI_ID_PERMISO_TOPICO NUMBER NOT NULL ENABLE
    ,FC_OPERACION VARCHAR2(50) NOT NULL ENABLE
    ,FC_DESCRIPCION VARCHAR2(80)
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
    ,CONSTRAINT FI_ID_PERMISO_TOPICO FOREIGN KEY (FI_ID_PERMISO_TOPICO) REFERENCES CT_PERMISO_TOPICO (FI_ID_PERMISO_TOPICO)
) TABLESPACE TS_CTRL_BO;



--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE TOPICOS CONSUMIDOR DE KAFKA
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_TOPICO_CONSUMIDOR_KAFKA
(
    FI_ID_TOPICO_KAFKA NUMBER NOT NULL ENABLE
    ,FI_ID_CONSUMIDOR_KAFKA NUMBER NOT NULL ENABLE
    ,FI_ID_PERMISO_TOPICO NUMBER NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
    ,CONSTRAINT FI_ID_TOPICO_KAFKA FOREIGN KEY (FI_ID_TOPICO_KAFKA) REFERENCES CT_TOPICO_KAFKA (FI_ID_TOPICO_KAFKA)
    ,CONSTRAINT FI_ID_CONSUMIDOR_KAFKA FOREIGN KEY (FI_ID_CONSUMIDOR_KAFKA) REFERENCES CT_CONSUMIDOR_KAFKA (FI_ID_CONSUMIDOR_KAFKA)
    ,CONSTRAINT FI_ID_PERMISO_TOPICO FOREIGN KEY (FI_ID_PERMISO_TOPICO) REFERENCES CT_PERMISO_TOPICO (FI_ID_PERMISO_TOPICO)
) TABLESPACE TS_CTRL_BO;



--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE ESQUEMAS DE TRANSACCIÓN
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_TRANSACCION_ESQUEMA
(
    FI_ID_TIPO_TRANSACCION NUMBER NOT NULL ENABLE
    ,FI_ID_ESQUEMA_AVRO NUMBER NOT NULL ENABLE
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
    ,CONSTRAINT FI_ID_TIPO_TRANSACCION FOREIGN KEY (FI_ID_TIPO_TRANSACCION) REFERENCES CT_TIPO_TRANSACCION (FI_ID_TIPO_TRANSACCION)
    ,CONSTRAINT FI_ID_ESQUEMA_AVRO FOREIGN KEY (FI_ID_ESQUEMA_AVRO) REFERENCES TA_ESQUEMA_AVRO (FI_ID_ESQUEMA_AVRO)
) TABLESPACE TS_CTRL_BO;



--------------------------------------------------------------------------------
------------------------------------------------------ TABLA DE EVENTOS DE COBRE BANCARIO
--------------------------------------------------------------------------------

CREATE TABLE URSCTRLBO.TA_EVENTOS_CB
(
    FI_ID_TRANSACCION NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL ENABLE
    ,FI_ID_USUARIO_REGISTRO NUMBER NOT NULL ENABLE
    ,FI_ID_ESTATUS_TRANSMISION NUMBER NOT NULL ENABLE
    ,FI_ID_TIPO_TRANSACCION NUMBER NOT NULL ENABLE
    ,FD_FECHA_REGISTRO DATE NOT NULL ENABLE
    ,FC_SISTEMA_REGISTRO VARCHAR2(50) NOT NULL ENABLE
    ,FC_JSON CLOB
    ,FC_ID_WORKER VARCHAR2(50)
    ,FD_FECHA_LECTURA DATE
    ,FD_FECHA_PROCESAMIENTO DATE
    ,FC_KAFKA_ID VARCHAR(20)
    ,FI_ESTATUS NUMBER DEFAULT 1 NOT NULL ENABLE
    ,FC_USERMOD VARCHAR2(50) DEFAULT USER NOT NULL ENABLE 
    ,FD_FECHAMOD DATE DEFAULT SYSDATE NOT NULL ENABLE
    ,CONSTRAINT FI_ID_USUARIO_REGISTRO FOREIGN KEY (FI_ID_USUARIO_REGISTRO) REFERENCES TA_USUARIOS_REGISTRO (FI_ID_USUARIO_REGISTRO)
    ,CONSTRAINT FI_ID_ESTATUS_TRANSMISION FOREIGN KEY (FI_ID_ESTATUS_TRANSMISION) REFERENCES CT_ESTATUS_TRANSMISION (FI_ID_ESTATUS_TRANSMISION)
    ,CONSTRAINT FI_ID_TIPO_TRANSACCION FOREIGN KEY (FI_ID_TIPO_TRANSACCION) REFERENCES CT_TIPO_TRANSACCION (FI_ID_TIPO_TRANSACCION)
) TABLESPACE TS_CTRL_BO;



--------------------------------------------------------------------------------
------------------------------------------------------ CONSTRAINTS DE LLAVES FORANEAS
--------------------------------------------------------------------------------